name: Code coverage
# See https://app.codecov.io/
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

